[platformio]
default_envs = reterminal_sticky

[env:reterminal_sticky]
platform = espressif32 @ 6.12.0
board = esp32-s3-devkitc-1
framework = arduino, espidf

board_build.mcu = esp32s3
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitions.csv
; CrossPoint sticky uses DIO. qio_opi made ROM print mode:QIO clock div:1
; then die in ets_loader.c 78 before the 2nd-stage bootloader ran.
board_build.arduino.memory_type = dio_opi
board_build.psram_type = opi

build_unflags =
  -std=gnu++11
  -Werror=int-in-bool-context
  -Werror
  -Werror=format-truncation
  -Werror=format

build_flags =
  -Wno-error
  -Wno-format-truncation
  -Wno-error=format-truncation
  -Wno-error=format
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DBOARD_HAS_PSRAM=1
  -DMINIZ_NO_ZLIB_COMPATIBLE_NAMES=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DDISABLE_FS_H_WARNING=1
  -DCORE_DEBUG_LEVEL=0
  -DRETERMINAL_STICKY=1
  -DCONFIG_NIMBLE_CPP_IDF=1
  -DCONFIG_BT_NIMBLE_LEGACY_VHCI_ENABLE=1
  -DOMIT_FONTS=1
  -DRELEASE_BUILD
  -I lib/hal
  -std=gnu++17

monitor_port = /dev/cu.wchusbserial5C850496161
monitor_speed = 115200
monitor_filters =
  esp32_exception_decoder

upload_protocol = esptool
upload_speed = 460800
upload_port = /dev/cu.wchusbserial5C850496161

extra_scripts =
  pre:scripts/pio_nowerror.py

lib_deps =
  h2zero/esp-nimble-cpp@2.3.4
